version: '3'
services:
  frontend:
    image: yprite/agilebuddy-frontend:latest
    # platform: linux/amd64
    ports:
      - "10180:80"
    restart: always

  backend:
    image: yprite/agilebuddy-backend:latest
    # platform: linux/amd64
    ports:
      - "10190:3001"
    restart: always